version: "2.1"
services:
  orion:
    user: root
    image: pegasyseng/orion:1.6.0
    environment:
      - ORION_NODEURL=${ORION_NODEURL}
    volumes:
      - ./orion:/config/orion
    command: ["/config/orion/orion.conf"]

  besu:
    user: root
    image: hyperledger/besu:21.1.3
    environment:
      - BESU_OPTS=-Xms2G -Xmx4G -XX:NewRatio=1 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8888 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    volumes:
      - ./besu:/config/besu
      - ../network:/network
      - ../network/static-nodes.json:/data/node/static-nodes.json
    command: ["--config-file=/config/besu/config.toml"]
  
  besu-regular:
    extends:
      service: besu
    environment:
      - BESU_PRIVACY_ENABLED=true
      - BESU_PRIVACY_FLEXIBLE_GROUPS_ENABLED=true